# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'news.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 871, 550))
        self.tabWidget.setMinimumSize(QtCore.QSize(661, 500))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"}\n"
"QTabWidget::tab-bar{\n"
"    alignment:left;\n"
"}\n"
"QTabBar::tab{\n"
"    color:white;\n"
"    background:rgb(0, 170, 255);\n"
"    min-width:150px;\n"
"    min-height:50px;\n"
"    font:13pt \'微软雅黑\';\n"
"}\n"
"QTabBar::tab:hover{\n"
"    color:rgb(0, 170, 255);\n"
"    background:rgb(255, 255, 255, 100);\n"
"}\n"
"QTabBar::tab:selected{\n"
"    border-color:rgb(0, 170, 255);\n"
"    background:white;\n"
"    color:rgb(0, 170, 255);\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setStyleSheet("")
        self.tab_1.setObjectName("tab_1")
        self.widget_1 = QtWidgets.QWidget(self.tab_1)
        self.widget_1.setGeometry(QtCore.QRect(0, 0, 871, 491))
        self.widget_1.setStyleSheet("")
        self.widget_1.setObjectName("widget_1")
        self.singleNewsPaperEdit = QtWidgets.QTextEdit(self.widget_1)
        self.singleNewsPaperEdit.setGeometry(QtCore.QRect(40, 110, 521, 301))
        self.singleNewsPaperEdit.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    border-width: 2px;\n"
"    border-color: #3D74BB;\n"
"    border-style: solid;\n"
"}")
        self.singleNewsPaperEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.singleNewsPaperEdit.setObjectName("singleNewsPaperEdit")
        self.singleFileButton = QtWidgets.QPushButton(self.widget_1)
        self.singleFileButton.setGeometry(QtCore.QRect(450, 30, 111, 51))
        self.singleFileButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.singleFileButton.setObjectName("singleFileButton")
        self.predictButton2 = QtWidgets.QPushButton(self.widget_1)
        self.predictButton2.setGeometry(QtCore.QRect(580, 220, 61, 51))
        self.predictButton2.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.predictButton2.setObjectName("predictButton2")
        self.layoutWidget = QtWidgets.QWidget(self.widget_1)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 420, 791, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget)
        self.clearButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-height:3em;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.predictButton = QtWidgets.QPushButton(self.layoutWidget)
        self.predictButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-height:3em;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout.addWidget(self.predictButton)
        self.exitButton = QtWidgets.QPushButton(self.layoutWidget)
        self.exitButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-height:3em;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.singleResultBroswer = QtWidgets.QTextBrowser(self.widget_1)
        self.singleResultBroswer.setGeometry(QtCore.QRect(670, 160, 161, 161))
        self.singleResultBroswer.setStyleSheet("background-color: white;\n"
"border-width: 2px;\n"
"border-color: #3D74BB;\n"
"border-style: solid;")
        self.singleResultBroswer.setObjectName("singleResultBroswer")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(40, 10, 61, 20))
        self.label.setStyleSheet("QLabel{\n"
"    color:#3D74BB;\n"
"    border: 2px solid blue;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_1)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 61, 20))
        self.label_2.setStyleSheet("QLabel{\n"
"    color:#3D74BB;\n"
"    border: 2px solid blue;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.singleNewslineEdit = QtWidgets.QLineEdit(self.widget_1)
        self.singleNewslineEdit.setGeometry(QtCore.QRect(40, 30, 401, 51))
        self.singleNewslineEdit.setStyleSheet("background-color: white;\n"
"border-width: 2px;\n"
"border-color: #3D74BB;\n"
"border-style: solid;")
        self.singleNewslineEdit.setObjectName("singleNewslineEdit")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 0, 871, 491))
        self.widget_4.setStyleSheet("table:center;")
        self.widget_4.setObjectName("widget_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.widget_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 420, 621, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mulityFileButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.mulityFileButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    min-height: 2em;\n"
"\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.mulityFileButton.setObjectName("mulityFileButton")
        self.horizontalLayout_2.addWidget(self.mulityFileButton)
        self.mulityPredictButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.mulityPredictButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    min-height: 2em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.mulityPredictButton.setObjectName("mulityPredictButton")
        self.horizontalLayout_2.addWidget(self.mulityPredictButton)
        self.downloadButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.downloadButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    min-height: 2em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_2.addWidget(self.downloadButton)
        self.loadingLine = QtWidgets.QProgressBar(self.widget_4)
        self.loadingLine.setGeometry(QtCore.QRect(30, 390, 621, 31))
        self.loadingLine.setStyleSheet("QProgressBar{\n"
"   border: 2px solid #2196F3;/*边框以及边框颜色*/\n"
"    border-radius: 5px;\n"
"    background-color: #E0E0E0;\n"
"\n"
"}\n"
"QProgressBar::chunk{\n"
" background-color: #2196F3;\n"
"    width: 10px; /*区块宽度*/\n"
"    margin: 0.5px;\n"
"\n"
"}\n"
"")
        self.loadingLine.setProperty("value", 24)
        self.loadingLine.setTextVisible(False)
        self.loadingLine.setObjectName("loadingLine")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(720, 10, 61, 20))
        self.label_3.setStyleSheet("QLabel{\n"
"    color:#3D74BB;\n"
"    border: 2px solid blue;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(300, 10, 61, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"    color:#3D74BB;\n"
"    border: 2px solid blue;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.mulityNewsTable = QtWidgets.QTableWidget(self.widget_4)
        self.mulityNewsTable.setGeometry(QtCore.QRect(30, 30, 621, 331))
        self.mulityNewsTable.setStyleSheet("/*\n"
"tabelwidget*/\n"
"QTableWidget{\n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"\n"
"    background-color: white;\n"
"    border-width: 2px;\n"
"    border-color: #3D74BB;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"/*选中item*/\n"
"QTableWidget::item:selected{\n"
"color:rgb(255, 255, 255);\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 rgb(0, 170, 255));\n"
"}\n"
"\n"
"/*\n"
"悬浮item*/\n"
"QTableWidget::item:hover{\n"
"background:rgb(0, 170, 255);\n"
"}\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"font: 14px;\n"
"padding:3px;\n"
"margin:0px;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}\n"
"\n"
"")
        self.mulityNewsTable.setObjectName("mulityNewsTable")
        self.mulityNewsTable.setColumnCount(2)
        self.mulityNewsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.mulityNewsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mulityNewsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mulityNewsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mulityNewsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mulityNewsTable.setItem(0, 1, item)
        self.mulityNewsTable.horizontalHeader().setDefaultSectionSize(275)
        self.mulityResultsTable = QtWidgets.QTableWidget(self.widget_4)
        self.mulityResultsTable.setGeometry(QtCore.QRect(660, 30, 181, 451))
        self.mulityResultsTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mulityResultsTable.setStyleSheet("/*\n"
"tabelwidget*/\n"
"QTableWidget{\n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"\n"
"    background-color: white;\n"
"    border-width: 2px;\n"
"    border-color: #3D74BB;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"/*选中item*/\n"
"QTableWidget::item:selected{\n"
"color:rgb(255, 255, 255);\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 rgb(0, 170, 255));\n"
"}\n"
"\n"
"/*\n"
"悬浮item*/\n"
"QTableWidget::item:hover{\n"
"background:rgb(0, 170, 255);\n"
"}\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"font: 14px;\n"
"padding:3px;\n"
"margin:0px;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}\n"
"\n"
"")
        self.mulityResultsTable.setObjectName("mulityResultsTable")
        self.mulityResultsTable.setColumnCount(1)
        self.mulityResultsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.mulityResultsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.mulityResultsTable.setHorizontalHeaderItem(0, item)
        self.mulityResultsTable.horizontalHeader().setDefaultSectionSize(150)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 871, 491))
        self.widget_3.setObjectName("widget_3")
        self.searchButton = QtWidgets.QPushButton(self.widget_3)
        self.searchButton.setGeometry(QtCore.QRect(250, 20, 71, 41))
        self.searchButton.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(0, 170, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton::pressed {\n"
"    background-color: white;\n"
"    color:rgb(0, 170, 255);\n"
"    border-style: inset;\n"
"}")
        self.searchButton.setObjectName("searchButton")
        self.searchlineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.searchlineEdit.setGeometry(QtCore.QRect(30, 20, 201, 41))
        self.searchlineEdit.setStyleSheet("background-color: white;\n"
"border-width: 2px;\n"
"border-color: #3D74BB;\n"
"border-style: solid;")
        self.searchlineEdit.setObjectName("searchlineEdit")
        self.sqliteTable = QtWidgets.QTableWidget(self.widget_3)
        self.sqliteTable.setGeometry(QtCore.QRect(30, 70, 821, 391))
        self.sqliteTable.setStyleSheet("/*\n"
"tabelwidget*/\n"
"QTableWidget{\n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"\n"
"    background-color: white;\n"
"    border-width: 2px;\n"
"    border-color: #3D74BB;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"/*选中item*/\n"
"QTableWidget::item:selected{\n"
"color:rgb(255, 255, 255);\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 rgb(0, 170, 255));\n"
"}\n"
"\n"
"/*\n"
"悬浮item*/\n"
"QTableWidget::item:hover{\n"
"background:rgb(0, 170, 255);\n"
"}\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"font: 14px;\n"
"padding:3px;\n"
"margin:0px;\n"
"border:1px solid #242424;\n"
"border-left-width:0;\n"
"}\n"
"\n"
"")
        self.sqliteTable.setObjectName("sqliteTable")
        self.sqliteTable.setColumnCount(4)
        self.sqliteTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.sqliteTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sqliteTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sqliteTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sqliteTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sqliteTable.setHorizontalHeaderItem(3, item)
        self.sqliteTable.horizontalHeader().setCascadingSectionResizes(False)
        self.sqliteTable.horizontalHeader().setDefaultSectionSize(198)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setGeometry(QtCore.QRect(0, 0, 871, 491))
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.widget_2 = QtWidgets.QWidget(self.tab_5)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 871, 491))
        self.widget_2.setObjectName("widget_2")
        self.introductionBroswer = QtWidgets.QTextBrowser(self.widget_2)
        self.introductionBroswer.setGeometry(QtCore.QRect(20, 20, 661, 381))
        self.introductionBroswer.setStyleSheet("background-color: white;\n"
"border-width: 2px;\n"
"border-color: #3D74BB;\n"
"border-style: solid;")
        self.introductionBroswer.setObjectName("introductionBroswer")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.singleFileButton.setText(_translate("MainWindow", "从文件导入"))
        self.predictButton2.setText(_translate("MainWindow", "->"))
        self.clearButton.setText(_translate("MainWindow", "清除全部内容"))
        self.predictButton.setText(_translate("MainWindow", "新闻文本预测"))
        self.exitButton.setText(_translate("MainWindow", "退出程序"))
        self.label.setText(_translate("MainWindow", "新闻标题"))
        self.label_2.setText(_translate("MainWindow", "新闻内容"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "单条预测"))
        self.mulityFileButton.setText(_translate("MainWindow", "导入文本"))
        self.mulityPredictButton.setText(_translate("MainWindow", "批量预测"))
        self.downloadButton.setText(_translate("MainWindow", "下载结果"))
        self.label_3.setText(_translate("MainWindow", "识别结果"))
        self.label_4.setText(_translate("MainWindow", "新闻列表"))
        item = self.mulityNewsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.mulityNewsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新闻标题"))
        item = self.mulityNewsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新闻内容"))
        __sortingEnabled = self.mulityNewsTable.isSortingEnabled()
        self.mulityNewsTable.setSortingEnabled(False)
        self.mulityNewsTable.setSortingEnabled(__sortingEnabled)
        item = self.mulityResultsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.mulityResultsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "预测结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "多条预测"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        item = self.sqliteTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.sqliteTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "预测分类"))
        item = self.sqliteTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "分所属类"))
        item = self.sqliteTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "新闻标题"))
        item = self.sqliteTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "新闻内容"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "数据查看"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "数据分析"))
        self.introductionBroswer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt;\">简介</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "关于我们"))
