# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 667)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setMinimumSize(QtCore.QSize(661, 500))
        self.mainTabWidget.setStyleSheet("QTabWidget::pane{\n"
                                         "}\n"
                                         "QTabWidget::tab-bar{\n"
                                         "    alignment:left;\n"
                                         "}\n"
                                         "QTabBar::tab{\n"
                                         "    color:white;\n"
                                         "    background:rgb(0, 170, 255);\n"
                                         "    min-width:175px;\n"
                                         "    min-height:70px;\n"
                                         "    font:12pt \'微软雅黑\';\n"
                                         "}\n"
                                         "QTabBar::tab:hover{\n"
                                         "    color:rgb(0, 170, 255);\n"
                                         "    background:rgb(255, 255, 255, 100);\n"
                                         "}\n"
                                         "QTabBar::tab:selected{\n"
                                         "    background:white;\n"
                                         "    color:rgb(0, 170, 255);\n"
                                         "}")
        self.mainTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainTabWidget.setUsesScrollButtons(False)
        self.mainTabWidget.setDocumentMode(False)
        self.mainTabWidget.setTabsClosable(False)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setStyleSheet("")
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_1 = QtWidgets.QWidget(self.tab_1)
        self.widget_1.setStyleSheet("")
        self.widget_1.setObjectName("widget_1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSpacing(10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(62, 0))
        self.label.setTabletTracking(False)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("QLabel{\n"
                                 "    color:#3D74BB;\n"
                                 "    border: 2px solid blue;\n"
                                 "    border-radius: 4px;\n"
                                 "    padding: 2px;\n"
                                 "    ScaledContents: true;\n"
                                 "}")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.singleNewslineEdit = QtWidgets.QLineEdit(self.widget_1)
        self.singleNewslineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.singleNewslineEdit.setStyleSheet("background-color: white;\n"
                                              "border-width: 2px;\n"
                                              "border-color: #3D74BB;\n"
                                              "border-style: solid;\n"
                                              "\n"
                                              "    font: 12pt \"微软雅黑\";\n"
                                              "\n"
                                              "    border-top-right-radius: 8px;\n"
                                              "    border-top-left-radius: 8px;\n"
                                              "    border-bottom-left-radius: 8px;\n"
                                              "    border-bottom-right-radius: 8px;")
        self.singleNewslineEdit.setObjectName("singleNewslineEdit")
        self.horizontalLayout_6.addWidget(self.singleNewslineEdit)
        self.singleFileButton = QtWidgets.QPushButton(self.widget_1)
        self.singleFileButton.setMinimumSize(QtCore.QSize(150, 0))
        self.singleFileButton.setMaximumSize(QtCore.QSize(200, 40))
        self.singleFileButton.setStyleSheet("QPushButton {\n"
                                            "    color:white;\n"
                                            "    background-color:rgb(0, 170, 255);\n"
                                            "    border-style: outset;\n"
                                            "    border-width: 2px;\n"
                                            "    border-radius: 10px;\n"
                                            "    border-color: beige;\n"
                                            "    font: bold 14px;\n"
                                            "    padding: 6px;\n"
                                            "\n"
                                            "    border-top-right-radius: 8px;\n"
                                            "    border-top-left-radius: 8px;\n"
                                            "    border-bottom-left-radius: 8px;\n"
                                            "    border-bottom-right-radius: 8px;\n"
                                            "}\n"
                                            "QPushButton::pressed {\n"
                                            "    background-color: white;\n"
                                            "    color:rgb(0, 170, 255);\n"
                                            "    border-style: inset;\n"
                                            "}")
        self.singleFileButton.setObjectName("singleFileButton")
        self.horizontalLayout_6.addWidget(self.singleFileButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.widget_1)
        self.label_2.setStyleSheet("QLabel{\n"
                                   "    color:#3D74BB;\n"
                                   "    border: 2px solid blue;\n"
                                   "    border-radius: 4px;\n"
                                   "    padding: 2px;\n"
                                   "\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.singleNewsPaperEdit = QtWidgets.QTextEdit(self.widget_1)
        self.singleNewsPaperEdit.setStyleSheet("QTextEdit {\n"
                                               "    background-color: white;\n"
                                               "    border-width: 2px;\n"
                                               "    border-color: #3D74BB;\n"
                                               "    border-style: solid;\n"
                                               "    border-top-right-radius: 8px;\n"
                                               "    border-top-left-radius: 8px;\n"
                                               "    border-bottom-left-radius: 8px;\n"
                                               "    border-bottom-right-radius: 8px;\n"
                                               "\n"
                                               "    font: 12pt \"微软雅黑\";\n"
                                               "}")
        self.singleNewsPaperEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.singleNewsPaperEdit.setObjectName("singleNewsPaperEdit")
        self.verticalLayout_4.addWidget(self.singleNewsPaperEdit)
        self.gridLayout_11.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.singleClearButton = QtWidgets.QPushButton(self.widget_1)
        self.singleClearButton.setStyleSheet("QPushButton {\n"
                                             "    color:white;\n"
                                             "    background-color:rgb(0, 170, 255);\n"
                                             "    border-style: outset;\n"
                                             "    border-width: 2px;\n"
                                             "    border-radius: 10px;\n"
                                             "    border-color: beige;\n"
                                             "    font: bold 14px;\n"
                                             "    min-height:3em;\n"
                                             "    min-width: 10em;\n"
                                             "    padding: 6px;\n"
                                             "}\n"
                                             "QPushButton::pressed {\n"
                                             "    background-color: white;\n"
                                             "    color:rgb(0, 170, 255);\n"
                                             "    border-style: inset;\n"
                                             "}")
        self.singleClearButton.setObjectName("singleClearButton")
        self.horizontalLayout.addWidget(self.singleClearButton)
        self.singleCheckButton = QtWidgets.QPushButton(self.widget_1)
        self.singleCheckButton.setStyleSheet("QPushButton {\n"
                                             "    color:white;\n"
                                             "    background-color:rgb(0, 170, 255);\n"
                                             "    border-style: outset;\n"
                                             "    border-width: 2px;\n"
                                             "    border-radius: 10px;\n"
                                             "    border-color: beige;\n"
                                             "    font: bold 14px;\n"
                                             "    min-height:3em;\n"
                                             "    min-width: 10em;\n"
                                             "    padding: 6px;\n"
                                             "}\n"
                                             "QPushButton::pressed {\n"
                                             "    background-color: white;\n"
                                             "    color:rgb(0, 170, 255);\n"
                                             "    border-style: inset;\n"
                                             "}")
        self.singleCheckButton.setObjectName("singleCheckButton")
        self.horizontalLayout.addWidget(self.singleCheckButton)
        self.singlePredictButton = QtWidgets.QPushButton(self.widget_1)
        self.singlePredictButton.setStyleSheet("QPushButton {\n"
                                               "    color:white;\n"
                                               "    background-color:rgb(0, 170, 255);\n"
                                               "    border-style: outset;\n"
                                               "    border-width: 2px;\n"
                                               "    border-radius: 10px;\n"
                                               "    border-color: beige;\n"
                                               "    font: bold 14px;\n"
                                               "    min-height:3em;\n"
                                               "    min-width: 10em;\n"
                                               "    padding: 6px;\n"
                                               "}\n"
                                               "QPushButton::pressed {\n"
                                               "    background-color: white;\n"
                                               "    color:rgb(0, 170, 255);\n"
                                               "    border-style: inset;\n"
                                               "}")
        self.singlePredictButton.setObjectName("singlePredictButton")
        self.horizontalLayout.addWidget(self.singlePredictButton)
        self.gridLayout_11.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.singlePredictButton2 = QtWidgets.QPushButton(self.widget_1)
        self.singlePredictButton2.setMaximumSize(QtCore.QSize(50, 50))
        self.singlePredictButton2.setStyleSheet("QPushButton {\n"
                                                "    color:white;\n"
                                                "    background-color:rgb(0, 170, 255);\n"
                                                "    border-style: outset;\n"
                                                "    border-width: 2px;\n"
                                                "    border-radius: 10px;\n"
                                                "    border-color: beige;\n"
                                                "    font: bold 14px;\n"
                                                "    padding: 6px;\n"
                                                "}\n"
                                                "QPushButton::pressed {\n"
                                                "    background-color: white;\n"
                                                "    color:rgb(0, 170, 255);\n"
                                                "    border-style: inset;\n"
                                                "}")
        self.singlePredictButton2.setObjectName("singlePredictButton2")
        self.horizontalLayout_9.addWidget(self.singlePredictButton2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet("QLabel{\n"
                                   "    color:#3D74BB;\n"
                                   "    border: 2px solid blue;\n"
                                   "    border-radius: 4px;\n"
                                   "    padding: 2px;\n"
                                   "}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.singlePredictResultLabel = QtWidgets.QLabel(self.widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singlePredictResultLabel.sizePolicy().hasHeightForWidth())
        self.singlePredictResultLabel.setSizePolicy(sizePolicy)
        self.singlePredictResultLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.singlePredictResultLabel.setStyleSheet("background-color: white;\n"
                                                    "border-width: 2px;\n"
                                                    "border-color: #3D74BB;\n"
                                                    "border-style: solid;\n"
                                                    "font: 25 24pt \"微软雅黑 Light\";\n"
                                                    "    border-top-right-radius: 8px;\n"
                                                    "    border-top-left-radius: 8px;\n"
                                                    "    border-bottom-left-radius: 8px;\n"
                                                    "    border-bottom-right-radius: 8px;")
        self.singlePredictResultLabel.setText("")
        self.singlePredictResultLabel.setObjectName("singlePredictResultLabel")
        self.verticalLayout_5.addWidget(self.singlePredictResultLabel)
        self.singleResultBroswer = QtWidgets.QTextBrowser(self.widget_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleResultBroswer.sizePolicy().hasHeightForWidth())
        self.singleResultBroswer.setSizePolicy(sizePolicy)
        self.singleResultBroswer.setMinimumSize(QtCore.QSize(0, 0))
        self.singleResultBroswer.setMaximumSize(QtCore.QSize(16777210, 73))
        self.singleResultBroswer.setStyleSheet("background-color: white;\n"
                                               "border-width: 2px;\n"
                                               "border-color: #3D74BB;\n"
                                               "border-style: solid;\n"
                                               "font: 25 24pt \"微软雅黑 Light\";\n"
                                               "    border-top-right-radius: 8px;\n"
                                               "    border-top-left-radius: 8px;\n"
                                               "    border-bottom-left-radius: 8px;\n"
                                               "    border-bottom-right-radius: 8px;")
        self.singleResultBroswer.setObjectName("singleResultBroswer")
        self.verticalLayout_5.addWidget(self.singleResultBroswer)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.setStretch(0, 10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.setStretch(0, 10)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        self.gridLayout_11.setColumnStretch(0, 10)
        self.gridLayout_11.setColumnStretch(1, 6)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_1, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.tab_2)
        self.widget_4.setStyleSheet("table:center;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.multiNewsTable = QtWidgets.QTableWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiNewsTable.sizePolicy().hasHeightForWidth())
        self.multiNewsTable.setSizePolicy(sizePolicy)
        self.multiNewsTable.setStyleSheet("/*tabelwidget*/\n"
                                          "QTableWidget{\n"
                                          "    \n"
                                          "    font: 12pt \"微软雅黑\";\n"
                                          "    border:1px solid #242424;\n"
                                          "    gridline-color:#242424;\n"
                                          "    background-color: white;\n"
                                          "    border-width: 2px;\n"
                                          "    border-color: #3D74BB;\n"
                                          "    border-style: solid;\n"
                                          "\n"
                                          "    border-top-right-radius: 8px;\n"
                                          "    border-top-left-radius: 8px;\n"
                                          "    border-bottom-left-radius: 8px;\n"
                                          "    border-bottom-right-radius: 8px;\n"
                                          "}\n"
                                          "\n"
                                          "/*选中item*/\n"
                                          "QTableWidget::item:selected{\n"
                                          "    color:rgb(255, 255, 255);\n"
                                          "    background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 rgb(0, 170, 255));\n"
                                          "}\n"
                                          "\n"
                                          "/*悬浮item*/\n"
                                          "QTableWidget::item:hover{\n"
                                          "    background:rgb(0, 170, 255);\n"
                                          "}\n"
                                          "/*表头*/\n"
                                          "QHeaderView::section{\n"
                                          "    text-align:center;\n"
                                          "    font: 14px;\n"
                                          "    padding:3px;\n"
                                          "    margin:0px;\n"
                                          "    border:1px solid #242424;\n"
                                          "    border-left-width:0;\n"
                                          "}\n"
                                          "\n"
                                          "")
        self.multiNewsTable.setShowGrid(True)
        self.multiNewsTable.setWordWrap(True)
        self.multiNewsTable.setObjectName("multiNewsTable")
        self.multiNewsTable.setColumnCount(2)
        self.multiNewsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.multiNewsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.multiNewsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.multiNewsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.multiNewsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.multiNewsTable.setItem(0, 1, item)
        self.multiNewsTable.horizontalHeader().setDefaultSectionSize(200)
        self.multiNewsTable.horizontalHeader().setStretchLastSection(True)
        self.multiNewsTable.verticalHeader().setDefaultSectionSize(50)
        self.gridLayout.addWidget(self.multiNewsTable, 0, 0, 1, 1)
        self.multiLoadingLine = QtWidgets.QProgressBar(self.widget_4)
        self.multiLoadingLine.setMinimumSize(QtCore.QSize(0, 30))
        self.multiLoadingLine.setStyleSheet("QProgressBar{\n"
                                            "   border: 2px solid #2196F3;/*边框以及边框颜色*/\n"
                                            "    border-radius: 5px;\n"
                                            "    background-color: #E0E0E0;\n"
                                            "\n"
                                            "}\n"
                                            "/*\n"
                                            "QProgressBar::chunk{\n"
                                            "    background-color: #2196F3;\n"
                                            "    width: 10px; \n"
                                            "    margin: 0.5px;\n"
                                            "\n"
                                            "}\n"
                                            "*/")
        self.multiLoadingLine.setProperty("value", 0)
        self.multiLoadingLine.setTextVisible(False)
        self.multiLoadingLine.setObjectName("multiLoadingLine")
        self.gridLayout.addWidget(self.multiLoadingLine, 1, 0, 1, 2)
        self.multiResultsTable = QtWidgets.QTableWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiResultsTable.sizePolicy().hasHeightForWidth())
        self.multiResultsTable.setSizePolicy(sizePolicy)
        self.multiResultsTable.setStyleSheet("/*tabelwidget*/\n"
                                             "QTableWidget{\n"
                                             "    \n"
                                             "    font: 12pt \"微软雅黑\";\n"
                                             "    border:1px solid #242424;\n"
                                             "    gridline-color:#242424;\n"
                                             "    background-color: white;\n"
                                             "    border-width: 2px;\n"
                                             "    border-color: #3D74BB;\n"
                                             "    border-style: solid;\n"
                                             "\n"
                                             "    border-top-right-radius: 8px;\n"
                                             "    border-top-left-radius: 8px;\n"
                                             "    border-bottom-left-radius: 8px;\n"
                                             "    border-bottom-right-radius: 8px;\n"
                                             "}\n"
                                             "\n"
                                             "/*选中item*/\n"
                                             "QTableWidget::item:selected{\n"
                                             "color:rgb(255, 255, 255);\n"
                                             "background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 rgb(0, 170, 255));\n"
                                             "}\n"
                                             "\n"
                                             "/*悬浮item*/\n"
                                             "QTableWidget::item:hover{\n"
                                             "background:rgb(0, 170, 255);\n"
                                             "}\n"
                                             "/*表头*/\n"
                                             "QHeaderView::section{\n"
                                             "text-align:center;\n"
                                             "font: 14px;\n"
                                             "padding:3px;\n"
                                             "margin:0px;\n"
                                             "border:1px solid #242424;\n"
                                             "border-left-width:0;\n"
                                             "}\n"
                                             "\n"
                                             "")
        self.multiResultsTable.setShowGrid(True)
        self.multiResultsTable.setWordWrap(True)
        self.multiResultsTable.setObjectName("multiResultsTable")
        self.multiResultsTable.setColumnCount(2)
        self.multiResultsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.multiResultsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.multiResultsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.multiResultsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.multiResultsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.multiResultsTable.setItem(0, 1, item)
        self.multiResultsTable.horizontalHeader().setDefaultSectionSize(100)
        self.multiResultsTable.horizontalHeader().setStretchLastSection(True)
        self.multiResultsTable.verticalHeader().setDefaultSectionSize(50)
        self.gridLayout.addWidget(self.multiResultsTable, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.multiFileButton = QtWidgets.QPushButton(self.widget_4)
        self.multiFileButton.setStyleSheet("QPushButton {\n"
                                           "    color:white;\n"
                                           "    background-color:rgb(0, 170, 255);\n"
                                           "    border-style: outset;\n"
                                           "    border-width: 2px;\n"
                                           "    border-radius: 10px;\n"
                                           "    border-color: beige;\n"
                                           "    font: bold 14px;\n"
                                           "    min-width: 10em;\n"
                                           "    min-height: 2em;\n"
                                           "\n"
                                           "    padding: 6px;\n"
                                           "}\n"
                                           "QPushButton::pressed {\n"
                                           "    background-color: white;\n"
                                           "    color:rgb(0, 170, 255);\n"
                                           "    border-style: inset;\n"
                                           "}")
        self.multiFileButton.setObjectName("multiFileButton")
        self.horizontalLayout_2.addWidget(self.multiFileButton)
        self.multiPredictButton = QtWidgets.QPushButton(self.widget_4)
        self.multiPredictButton.setStyleSheet("QPushButton {\n"
                                              "    color:white;\n"
                                              "    background-color:rgb(0, 170, 255);\n"
                                              "    border-style: outset;\n"
                                              "    border-width: 2px;\n"
                                              "    border-radius: 10px;\n"
                                              "    border-color: beige;\n"
                                              "    font: bold 14px;\n"
                                              "    min-width: 10em;\n"
                                              "    min-height: 2em;\n"
                                              "    padding: 6px;\n"
                                              "}\n"
                                              "QPushButton::pressed {\n"
                                              "    background-color: white;\n"
                                              "    color:rgb(0, 170, 255);\n"
                                              "    border-style: inset;\n"
                                              "}")
        self.multiPredictButton.setObjectName("multiPredictButton")
        self.horizontalLayout_2.addWidget(self.multiPredictButton)
        self.multiSaveButton = QtWidgets.QPushButton(self.widget_4)
        self.multiSaveButton.setStyleSheet("QPushButton {\n"
                                           "    color:white;\n"
                                           "    background-color:rgb(0, 170, 255);\n"
                                           "    border-style: outset;\n"
                                           "    border-width: 2px;\n"
                                           "    border-radius: 10px;\n"
                                           "    border-color: beige;\n"
                                           "    font: bold 14px;\n"
                                           "    min-width: 10em;\n"
                                           "    min-height: 2em;\n"
                                           "    padding: 6px;\n"
                                           "}\n"
                                           "QPushButton::pressed {\n"
                                           "    background-color: white;\n"
                                           "    color:rgb(0, 170, 255);\n"
                                           "    border-style: inset;\n"
                                           "}")
        self.multiSaveButton.setObjectName("multiSaveButton")
        self.horizontalLayout_2.addWidget(self.multiSaveButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 100)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchLineEdit = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        self.searchLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.searchLineEdit.setMaximumSize(QtCore.QSize(750, 50))
        self.searchLineEdit.setStyleSheet("background-color: white;\n"
                                          "border-width: 2px;\n"
                                          "border-color: #3D74BB;\n"
                                          "border-style: solid;\n"
                                          "\n"
                                          "    border-top-right-radius: 8px;\n"
                                          "    border-top-left-radius: 8px;\n"
                                          "    border-bottom-left-radius: 8px;\n"
                                          "    border-bottom-right-radius: 8px;")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout_4.addWidget(self.searchLineEdit)
        self.searchButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(70, 0))
        self.searchButton.setMaximumSize(QtCore.QSize(100, 50))
        self.searchButton.setStyleSheet("QPushButton {\n"
                                        "    color:white;\n"
                                        "    background-color:rgb(0, 170, 255);\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: beige;\n"
                                        "    font: bold 14px;\n"
                                        "    padding: 6px;\n"
                                        "}\n"
                                        "QPushButton::pressed {\n"
                                        "    background-color: white;\n"
                                        "    color:rgb(0, 170, 255);\n"
                                        "    border-style: inset;\n"
                                        "}")
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_4.addWidget(self.searchButton)
        self.searchClearButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchClearButton.sizePolicy().hasHeightForWidth())
        self.searchClearButton.setSizePolicy(sizePolicy)
        self.searchClearButton.setMinimumSize(QtCore.QSize(70, 0))
        self.searchClearButton.setMaximumSize(QtCore.QSize(100, 50))
        self.searchClearButton.setStyleSheet("QPushButton {\n"
                                             "    color:white;\n"
                                             "    background-color:rgb(0, 170, 255);\n"
                                             "    border-style: outset;\n"
                                             "    border-width: 2px;\n"
                                             "    border-radius: 10px;\n"
                                             "    border-color: beige;\n"
                                             "    font: bold 14px;\n"
                                             "    padding: 6px;\n"
                                             "}\n"
                                             "QPushButton::pressed {\n"
                                             "    background-color: white;\n"
                                             "    color:rgb(0, 170, 255);\n"
                                             "    border-style: inset;\n"
                                             "}")
        self.searchClearButton.setObjectName("searchClearButton")
        self.horizontalLayout_4.addWidget(self.searchClearButton)
        self.searchF1Result = QtWidgets.QLineEdit(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchF1Result.sizePolicy().hasHeightForWidth())
        self.searchF1Result.setSizePolicy(sizePolicy)
        self.searchF1Result.setMaximumSize(QtCore.QSize(100, 50))
        self.searchF1Result.setStyleSheet("background-color: white;\n"
                                          "border-width: 2px;\n"
                                          "border-color: #3D74BB;\n"
                                          "border-style: solid;\n"
                                          "\n"
                                          "    border-top-right-radius: 8px;\n"
                                          "    border-top-left-radius: 8px;\n"
                                          "    border-bottom-left-radius: 8px;\n"
                                          "    border-bottom-right-radius: 8px;")
        self.searchF1Result.setObjectName("searchF1Result")
        self.horizontalLayout_4.addWidget(self.searchF1Result)
        self.searchF1Button = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchF1Button.sizePolicy().hasHeightForWidth())
        self.searchF1Button.setSizePolicy(sizePolicy)
        self.searchF1Button.setMinimumSize(QtCore.QSize(100, 0))
        self.searchF1Button.setMaximumSize(QtCore.QSize(100, 50))
        self.searchF1Button.setStyleSheet("QPushButton {\n"
                                          "    color:white;\n"
                                          "    background-color:rgb(0, 170, 255);\n"
                                          "    border-style: outset;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 10px;\n"
                                          "    border-color: beige;\n"
                                          "    font: bold 14px;\n"
                                          "    padding: 6px;\n"
                                          "}\n"
                                          "QPushButton::pressed {\n"
                                          "    background-color: white;\n"
                                          "    color:rgb(0, 170, 255);\n"
                                          "    border-style: inset;\n"
                                          "}")
        self.searchF1Button.setObjectName("searchF1Button")
        self.horizontalLayout_4.addWidget(self.searchF1Button)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.searchCheckButton = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchCheckButton.sizePolicy().hasHeightForWidth())
        self.searchCheckButton.setSizePolicy(sizePolicy)
        self.searchCheckButton.setMinimumSize(QtCore.QSize(100, 0))
        self.searchCheckButton.setMaximumSize(QtCore.QSize(100, 50))
        self.searchCheckButton.setStyleSheet("QPushButton {\n"
                                             "    color:white;\n"
                                             "    background-color:rgb(0, 170, 255);\n"
                                             "    border-style: outset;\n"
                                             "    border-width: 2px;\n"
                                             "    border-radius: 10px;\n"
                                             "    border-color: beige;\n"
                                             "    font: bold 14px;\n"
                                             "    padding: 6px;\n"
                                             "}\n"
                                             "QPushButton::pressed {\n"
                                             "    background-color: white;\n"
                                             "    color:rgb(0, 170, 255);\n"
                                             "    border-style: inset;\n"
                                             "}")
        self.searchCheckButton.setObjectName("searchCheckButton")
        self.horizontalLayout_4.addWidget(self.searchCheckButton)
        self.horizontalLayout_4.setStretch(0, 20)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.searchDBTable = QtWidgets.QTableWidget(self.widget_3)
        self.searchDBTable.setStyleSheet("/*tabelwidget*/\n"
                                         "QTableWidget{\n"
                                         "    font: 12pt \"微软雅黑\";\n"
                                         "    border:1px solid #242424;\n"
                                         "    gridline-color:#242424;\n"
                                         "    background-color: white;\n"
                                         "    border-width: 2px;\n"
                                         "    border-color: #3D74BB;\n"
                                         "    border-style: solid;\n"
                                         "\n"
                                         "    border-top-right-radius: 8px;\n"
                                         "    border-top-left-radius: 8px;\n"
                                         "    border-bottom-left-radius: 8px;\n"
                                         "    border-bottom-right-radius: 8px;\n"
                                         "}\n"
                                         "\n"
                                         "/*选中item*/\n"
                                         "QTableWidget::item:selected{\n"
                                         "color:rgb(255, 255, 255);\n"
                                         "background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 rgb(0, 170, 255));\n"
                                         "}\n"
                                         "\n"
                                         "/*悬浮item*/\n"
                                         "QTableWidget::item:hover{\n"
                                         "background:rgb(0, 170, 255);\n"
                                         "}\n"
                                         "/*表头*/\n"
                                         "QHeaderView::section{\n"
                                         "text-align:center;\n"
                                         "font: 14px;\n"
                                         "padding:3px;\n"
                                         "margin:0px;\n"
                                         "border:1px solid #242424;\n"
                                         "border-left-width:0;\n"
                                         "}\n"
                                         "\n"
                                         "")
        self.searchDBTable.setObjectName("searchDBTable")
        self.searchDBTable.setColumnCount(4)
        self.searchDBTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.searchDBTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDBTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDBTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDBTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.searchDBTable.setHorizontalHeaderItem(3, item)
        self.searchDBTable.horizontalHeader().setCascadingSectionResizes(False)
        self.searchDBTable.horizontalHeader().setDefaultSectionSize(198)
        self.searchDBTable.horizontalHeader().setStretchLastSection(True)
        self.searchDBTable.verticalHeader().setDefaultSectionSize(50)
        self.verticalLayout.addWidget(self.searchDBTable)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 100)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setObjectName("widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.wordCloudSrc = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordCloudSrc.sizePolicy().hasHeightForWidth())
        self.wordCloudSrc.setSizePolicy(sizePolicy)
        self.wordCloudSrc.setMinimumSize(QtCore.QSize(70, 50))
        self.wordCloudSrc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wordCloudSrc.setStyleSheet("QComboBox{\n"
                                        "    align: center;\n"
                                        "    font: 25 12pt \"微软雅黑 Light\";\n"
                                        "    color:#3D74BB;\n"
                                        "    border: 2px solid blue;\n"
                                        "    border-radius: 4px;\n"
                                        "    padding: 2px;\n"
                                        "    font: 14px;\n"
                                        "}")
        self.wordCloudSrc.setObjectName("wordCloudSrc")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.wordCloudSrc.addItem("")
        self.horizontalLayout_3.addWidget(self.wordCloudSrc)
        self.wordCloudMask = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordCloudMask.sizePolicy().hasHeightForWidth())
        self.wordCloudMask.setSizePolicy(sizePolicy)
        self.wordCloudMask.setMaximumSize(QtCore.QSize(300, 16777215))
        self.wordCloudMask.setStyleSheet("background-color: white;\n"
                                         "    border-width: 2px;\n"
                                         "    border-color: #3D74BB;\n"
                                         "    border-style: solid;\n"
                                         "    border-top-right-radius: 8px;\n"
                                         "    border-top-left-radius: 8px;\n"
                                         "    border-bottom-left-radius: 8px;\n"
                                         "    border-bottom-right-radius: 8px;")
        self.wordCloudMask.setObjectName("wordCloudMask")
        self.horizontalLayout_3.addWidget(self.wordCloudMask)
        self.wordCloudMaskSelectButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordCloudMaskSelectButton.sizePolicy().hasHeightForWidth())
        self.wordCloudMaskSelectButton.setSizePolicy(sizePolicy)
        self.wordCloudMaskSelectButton.setMinimumSize(QtCore.QSize(100, 0))
        self.wordCloudMaskSelectButton.setMaximumSize(QtCore.QSize(100, 50))
        self.wordCloudMaskSelectButton.setStyleSheet("QPushButton {\n"
                                                     "    color:white;\n"
                                                     "    background-color:rgb(0, 170, 255);\n"
                                                     "    border-style: outset;\n"
                                                     "    border-width: 2px;\n"
                                                     "    border-radius: 10px;\n"
                                                     "    border-color: beige;\n"
                                                     "    font: bold 14px;\n"
                                                     "    padding: 6px;\n"
                                                     "}\n"
                                                     "QPushButton::pressed {\n"
                                                     "    background-color: white;\n"
                                                     "    color:rgb(0, 170, 255);\n"
                                                     "    border-style: inset;\n"
                                                     "}")
        self.wordCloudMaskSelectButton.setObjectName("wordCloudMaskSelectButton")
        self.horizontalLayout_3.addWidget(self.wordCloudMaskSelectButton)
        self.wordDrawButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordDrawButton.sizePolicy().hasHeightForWidth())
        self.wordDrawButton.setSizePolicy(sizePolicy)
        self.wordDrawButton.setMinimumSize(QtCore.QSize(100, 0))
        self.wordDrawButton.setMaximumSize(QtCore.QSize(100, 50))
        self.wordDrawButton.setStyleSheet("QPushButton {\n"
                                          "    color:white;\n"
                                          "    background-color:rgb(0, 170, 255);\n"
                                          "    border-style: outset;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 10px;\n"
                                          "    border-color: beige;\n"
                                          "    font: bold 14px;\n"
                                          "    padding: 6px;\n"
                                          "}\n"
                                          "QPushButton::pressed {\n"
                                          "    background-color: white;\n"
                                          "    color:rgb(0, 170, 255);\n"
                                          "    border-style: inset;\n"
                                          "}")
        self.wordDrawButton.setObjectName("wordDrawButton")
        self.horizontalLayout_3.addWidget(self.wordDrawButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.wordCloudTabWidget = QtWidgets.QTabWidget(self.widget)
        self.wordCloudTabWidget.setStyleSheet("QTabWidget::pane{\n"
                                              "}\n"
                                              "QTabWidget::tab-bar{\n"
                                              "    alignment:left;\n"
                                              "}\n"
                                              "QTabBar::tab{\n"
                                              "    min-width:80px;\n"
                                              "    min-height:30px;\n"
                                              "    font:13pt \'微软雅黑\';\n"
                                              "    background: rgb(255, 170, 0);\n"
                                              "    color: white;\n"
                                              "}\n"
                                              "QTabBar::tab:hover{\n"
                                              "    color:rgb(255, 170, 0);\n"
                                              "    background: white;\n"
                                              "}\n"
                                              "QTabBar::tab:selected{\n"
                                              "    border-color: rgb(255, 170, 0);\n"
                                              "    background: white;\n"
                                              "    color: rgb(255, 170, 0);\n"
                                              "}")
        self.wordCloudTabWidget.setObjectName("wordCloudTabWidget")
        self.WordCloudTab = QtWidgets.QWidget()
        self.WordCloudTab.setObjectName("WordCloudTab")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.WordCloudTab)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.WordCloudWidget = MatplotlibWidget(self.WordCloudTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WordCloudWidget.sizePolicy().hasHeightForWidth())
        self.WordCloudWidget.setSizePolicy(sizePolicy)
        self.WordCloudWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                           "\n"
                                           "    border-top-right-radius: 8px;\n"
                                           "    border-top-left-radius: 8px;\n"
                                           "    border-bottom-left-radius: 8px;\n"
                                           "    border-bottom-right-radius: 8px;")
        self.WordCloudWidget.setObjectName("WordCloudWidget")
        self.gridLayout_23.addWidget(self.WordCloudWidget, 0, 0, 1, 1)
        self.wordCloudTabWidget.addTab(self.WordCloudTab, "")
        self.WordCountTab = QtWidgets.QWidget()
        self.WordCountTab.setObjectName("WordCountTab")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.WordCountTab)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.WordCountWidget = MatplotlibWidget(self.WordCountTab)
        self.WordCountWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                           "\n"
                                           "    border-top-right-radius: 8px;\n"
                                           "    border-top-left-radius: 8px;\n"
                                           "    border-bottom-left-radius: 8px;\n"
                                           "    border-bottom-right-radius: 8px;")
        self.WordCountWidget.setObjectName("WordCountWidget")
        self.gridLayout_24.addWidget(self.WordCountWidget, 0, 0, 1, 1)
        self.wordCloudTabWidget.addTab(self.WordCountTab, "")
        self.verticalLayout_3.addWidget(self.wordCloudTabWidget)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widget, 1, 0, 1, 1)
        self.mainTabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.tab_5)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.introTextBrowser = QtWidgets.QTextBrowser(self.widget_2)
        self.introTextBrowser.setMinimumSize(QtCore.QSize(600, 161))
        self.introTextBrowser.setMaximumSize(QtCore.QSize(16777215, 161))
        self.introTextBrowser.setStyleSheet("background-color: white;\n"
                                            "font: 25 16pt \"微软雅黑 Light\";\n"
                                            "border-width: 2px;\n"
                                            "border-color: #3D74BB;\n"
                                            "border-style: solid;\n"
                                            "\n"
                                            "    border-top-right-radius: 8px;\n"
                                            "    border-top-left-radius: 8px;\n"
                                            "    border-bottom-left-radius: 8px;\n"
                                            "    border-bottom-right-radius: 8px;")
        self.introTextBrowser.setObjectName("introTextBrowser")
        self.gridLayout_13.addWidget(self.introTextBrowser, 0, 0, 1, 1)
        self.introLogoLabel = QtWidgets.QLabel(self.widget_2)
        self.introLogoLabel.setMinimumSize(QtCore.QSize(161, 161))
        self.introLogoLabel.setMaximumSize(QtCore.QSize(16777215, 161))
        self.introLogoLabel.setStyleSheet("background-color: rgb(255, 170, 0)")
        self.introLogoLabel.setObjectName("introLogoLabel")
        self.gridLayout_13.addWidget(self.introLogoLabel, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget_2, 0, 0, 1, 1)
        self.mainTabWidget.addTab(self.tab_5, "")
        self.gridLayout_4.addWidget(self.mainTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        self.wordCloudTabWidget.setCurrentIndex(0)
        self.searchClearButton.clicked.connect(self.searchLineEdit.clear)
        self.searchClearButton.clicked.connect(self.searchF1Result.clear)
        self.singleClearButton.clicked.connect(self.singleNewsPaperEdit.clear)
        self.singleClearButton.clicked.connect(self.singleNewslineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mainTabWidget, self.singleNewslineEdit)
        MainWindow.setTabOrder(self.singleNewslineEdit, self.singleNewsPaperEdit)
        MainWindow.setTabOrder(self.singleNewsPaperEdit, self.singleFileButton)
        MainWindow.setTabOrder(self.singleFileButton, self.singleClearButton)
        MainWindow.setTabOrder(self.singleClearButton, self.singleCheckButton)
        MainWindow.setTabOrder(self.singleCheckButton, self.singlePredictButton)
        MainWindow.setTabOrder(self.singlePredictButton, self.singlePredictButton2)
        MainWindow.setTabOrder(self.singlePredictButton2, self.singleResultBroswer)
        MainWindow.setTabOrder(self.singleResultBroswer, self.multiNewsTable)
        MainWindow.setTabOrder(self.multiNewsTable, self.multiResultsTable)
        MainWindow.setTabOrder(self.multiResultsTable, self.multiFileButton)
        MainWindow.setTabOrder(self.multiFileButton, self.multiPredictButton)
        MainWindow.setTabOrder(self.multiPredictButton, self.multiSaveButton)
        MainWindow.setTabOrder(self.multiSaveButton, self.searchLineEdit)
        MainWindow.setTabOrder(self.searchLineEdit, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.searchClearButton)
        MainWindow.setTabOrder(self.searchClearButton, self.searchF1Result)
        MainWindow.setTabOrder(self.searchF1Result, self.searchF1Button)
        MainWindow.setTabOrder(self.searchF1Button, self.searchDBTable)
        MainWindow.setTabOrder(self.searchDBTable, self.wordCloudSrc)
        MainWindow.setTabOrder(self.wordCloudSrc, self.wordCloudMask)
        MainWindow.setTabOrder(self.wordCloudMask, self.wordCloudMaskSelectButton)
        MainWindow.setTabOrder(self.wordCloudMaskSelectButton, self.wordDrawButton)
        MainWindow.setTabOrder(self.wordDrawButton, self.wordCloudTabWidget)
        MainWindow.setTabOrder(self.wordCloudTabWidget, self.introTextBrowser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Meows - 一个优雅的新闻文本【分类预测&数据分析&词云生成】软件"))
        self.label.setText(_translate("MainWindow", "新闻标题"))
        self.singleFileButton.setText(_translate("MainWindow", "从文件导入"))
        self.label_2.setText(_translate("MainWindow", "新闻内容"))
        self.singleClearButton.setText(_translate("MainWindow", "清除全部内容"))
        self.singleCheckButton.setText(_translate("MainWindow", "数据统计"))
        self.singlePredictButton.setText(_translate("MainWindow", "新闻文本预测"))
        self.singlePredictButton2.setText(_translate("MainWindow", "->"))
        self.label_5.setText(_translate("MainWindow", "预测结果"))
        self.singleResultBroswer.setHtml(_translate("MainWindow",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'微软雅黑 Light\'; font-size:24pt; font-weight:24; font-style:normal;\">\n"
                                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请输入新闻</p></body></html>"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_1), _translate("MainWindow", "单条预测"))
        item = self.multiNewsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.multiNewsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "新闻标题"))
        item = self.multiNewsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "新闻内容"))
        __sortingEnabled = self.multiNewsTable.isSortingEnabled()
        self.multiNewsTable.setSortingEnabled(False)
        self.multiNewsTable.setSortingEnabled(__sortingEnabled)
        item = self.multiResultsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.multiResultsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "预测分类"))
        item = self.multiResultsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "原分类"))
        __sortingEnabled = self.multiResultsTable.isSortingEnabled()
        self.multiResultsTable.setSortingEnabled(False)
        self.multiResultsTable.setSortingEnabled(__sortingEnabled)
        self.multiFileButton.setText(_translate("MainWindow", "导入文本"))
        self.multiPredictButton.setText(_translate("MainWindow", "批量预测"))
        self.multiSaveButton.setText(_translate("MainWindow", "导出结果"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_2), _translate("MainWindow", "多条预测"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        self.searchClearButton.setText(_translate("MainWindow", "清空"))
        self.searchF1Button.setText(_translate("MainWindow", "f1Score"))
        self.searchCheckButton.setText(_translate("MainWindow", "数据统计"))
        item = self.searchDBTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.searchDBTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "预测分类"))
        item = self.searchDBTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "原分类"))
        item = self.searchDBTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "新闻标题"))
        item = self.searchDBTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "新闻内容"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_3), _translate("MainWindow", "数据分析"))
        self.wordCloudSrc.setItemText(0, _translate("MainWindow", "财经"))
        self.wordCloudSrc.setItemText(1, _translate("MainWindow", "房产"))
        self.wordCloudSrc.setItemText(2, _translate("MainWindow", "教育"))
        self.wordCloudSrc.setItemText(3, _translate("MainWindow", "科技"))
        self.wordCloudSrc.setItemText(4, _translate("MainWindow", "军事"))
        self.wordCloudSrc.setItemText(5, _translate("MainWindow", "汽车"))
        self.wordCloudSrc.setItemText(6, _translate("MainWindow", "体育"))
        self.wordCloudSrc.setItemText(7, _translate("MainWindow", "游戏"))
        self.wordCloudSrc.setItemText(8, _translate("MainWindow", "娱乐"))
        self.wordCloudSrc.setItemText(9, _translate("MainWindow", "其他"))
        self.wordCloudMaskSelectButton.setText(_translate("MainWindow", "选择蒙版"))
        self.wordDrawButton.setText(_translate("MainWindow", "绘制"))
        self.wordCloudTabWidget.setTabText(self.wordCloudTabWidget.indexOf(self.WordCloudTab),
                                           _translate("MainWindow", "词云"))
        self.wordCloudTabWidget.setTabText(self.wordCloudTabWidget.indexOf(self.WordCountTab),
                                           _translate("MainWindow", "统计"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_4), _translate("MainWindow", "热力词云"))
        self.introTextBrowser.setHtml(_translate("MainWindow",
                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                 "p, li { white-space: pre-wrap; }\n"
                                                 "</style></head><body style=\" font-family:\'微软雅黑 Light\'; font-size:16pt; font-weight:24; font-style:normal;\">\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">这里是Meows团队~</p>\n"
                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">又是元气满满的一天呢！</p>\n"
                                                 "<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Meow001</p>\n"
                                                 "<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">greetings from 4 a.m.~</p></body></html>"))
        self.introLogoLabel.setText(_translate("MainWindow", "LOGO"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_5), _translate("MainWindow", "关于我们"))


from ui.matplotlibwidget import MatplotlibWidget
